import Navbar from "@/components/Navbar";
import "./globals.css";
import Providers from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
				<Navbar />
				<main className="flex flex-col grainy-light min-h-[calc(100vh-3.5rem-1px)]">
					<div className="flex flex-1 flex-col h-full">
						<Providers>
							{children}
						</Providers>
					</div>
          <Toaster />
				</main>
			</body>
    </html>
  );
}
